package progressbar;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Color;
import java.util.HashMap;
import java.util.Map;
import javax.swing.*;

/**
 *
 * @author Timmy
 */
public class ProgressBarFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form ProgressBarFrame1
     */
    public ProgressBarFrame1() {
        initComponents();
//        new InformationPanel("Video1");
//        new InformationPanel("Video2");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainProgressBar = new javax.swing.JProgressBar();
        videoLength = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jScrollPane = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        javax.swing.JPanel emptyPanel = new javax.swing.JPanel();
        emptyPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(null);
        setResizable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(mainProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(mainProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                                .addContainerGap())
        );

        jRadioButton1.setText("Show Detail");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jScrollPane.setAutoscrolls(true);

        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);

        jScrollPane.setViewportView(jPanel2);
        jPanel2.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(emptyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(emptyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jRadioButton1))
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 353, Short.MAX_VALUE))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(6, 6, 6)
                                                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(11, Short.MAX_VALUE))
        );


        // remove horizontal scroll bar
        jScrollPane.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        labelToPanel = new HashMap<>();
        // default label to empty panel pair
        defaultLabel = new javax.swing.JLabel("Default");
        labelToPanel.put(defaultLabel, emptyPanel);

        selectedLabel = defaultLabel;
        pack();
    }// </editor-fold>

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        boolean visibility;
        int jFrameHeight;
        if (jRadioButton1.isSelected()) {
            visibility = false;
            jFrameHeight = this.getHeight() - DELTA_HEIGHT;
        } else {
            visibility = true;
            jFrameHeight = this.getHeight() + DELTA_HEIGHT;
        }
        jScrollPane.setVisible(visibility);
        labelToPanel.get(selectedLabel).setVisible(visibility);
        selectedLabel.setBackground(DEFAULT_TAG_COLOR);
        selectedLabel = defaultLabel;
        this.setSize(this.getWidth(), jFrameHeight);
    }

    private void menuLabelMouseEntered(java.awt.event.MouseEvent evt) {
        if (!evt.getComponent().equals(selectedLabel)) {
            ((javax.swing.JLabel) evt.getSource()).setBackground(new Color(224, 238, 224));
        }
    }

    private void menuLabelMouseExited(java.awt.event.MouseEvent evt) {
        if (!evt.getComponent().equals(selectedLabel)) {
            ((javax.swing.JLabel) evt.getSource()).setBackground(DEFAULT_TAG_COLOR);
        }
    }

    // when user want to select a tag
    private void menuLabelMouseClicked(java.awt.event.MouseEvent evt) {
        if (!evt.getComponent().equals(selectedLabel)) {
            selectedLabel.setBackground(DEFAULT_TAG_COLOR);
        }
        selectedLabel = (JLabel) evt.getComponent();
        selectedLabel.setBackground(new Color(238, 130, 238));
    }

    // when user do not want to select any tag
    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {
        if (!selectedLabel.equals(defaultLabel)) {
            selectedLabel.setBackground(DEFAULT_TAG_COLOR);
            labelToPanel.get(selectedLabel).setVisible(false);
            labelToPanel.get(defaultLabel).setVisible(true);
            selectedLabel = defaultLabel;
        }
    }

    private JProgressBar getMainProgressBar() {
        return this.mainProgressBar;
    }

    private InformationPanel createTask() {
        return null;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgressBarFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgressBarFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgressBarFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgressBarFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgressBarFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar mainProgressBar;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel videoLength;
    // End of variables declaration
    // custom variables
    private final int DELTA_HEIGHT = 281;
    private final Color DEFAULT_TAG_COLOR = new Color(255, 255, 255);
    private javax.swing.JLabel selectedLabel;
    private javax.swing.JLabel defaultLabel;
    private Map<javax.swing.JLabel, javax.swing.JPanel> labelToPanel;
    private javax.swing.GroupLayout jPanel2Layout;

    public class InformationPanel {
        private javax.swing.JProgressBar jProgressBar2;
        private javax.swing.JLabel jLabel12; // current time label
        public InformationPanel(String name) {
            // create label
            javax.swing.JLabel menuLabel = new javax.swing.JLabel();
            menuLabel.setBackground(new java.awt.Color(255, 255, 255));
            menuLabel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
            menuLabel.setText(name);
            menuLabel.setOpaque(true);
            menuLabel.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    menuLabelMouseClicked(evt);
                }
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    menuLabelMouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    menuLabelMouseExited(evt);
                }
            });
            jPanel2Layout.setHorizontalGroup(
                    jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(menuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 29, Short.MAX_VALUE))
            );
            jPanel2Layout.setVerticalGroup(
                    jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(menuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 267, Short.MAX_VALUE))
            );
            // create panel
            javax.swing.JPanel jPanel3 = new javax.swing.JPanel();;
            jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
            javax.swing.JLabel videoName = new javax.swing.JLabel();
            videoName.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            videoName.setText(name);
            javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
            javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
            javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
            javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
            javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
            javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
            javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
            javax.swing.JLabel jLabel9 = new javax.swing.JLabel();
            javax.swing.JLabel jLabel10 = new javax.swing.JLabel();
            javax.swing.JLabel jLabel11 = new javax.swing.JLabel();
            jLabel12 = new javax.swing.JLabel();
            jProgressBar2 = new javax.swing.JProgressBar();
            javax.swing.JSeparator jSeparator1 = new javax.swing.JSeparator();
            jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
            jLabel3.setText("Length");

            videoLength.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
            videoLength.setText("1:40 ");

            jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
            jLabel2.setText("Minutes");

            jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
            jLabel4.setText("Progress");

            jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
            jLabel5.setText("Frames");

            jLabel6.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
            jLabel6.setText("23");

            jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
            jLabel7.setText("Resolution");

            jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
            jLabel8.setText("320*180");

            jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
            jLabel9.setText("Output Format");

            jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
            jLabel10.setText(".VOB");

            jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
            jLabel11.setText("Current Time");

            jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
            jLabel12.setText("00:00:00");

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                    jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(videoName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jProgressBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                                                    .addComponent(videoLength)
                                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                    .addComponent(jLabel2))
                                                                            .addComponent(jLabel3)
                                                                            .addComponent(jLabel11)
                                                                            .addComponent(jLabel12))
                                                                    .addGap(65, 65, 65)
                                                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                            .addComponent(jLabel5)
                                                                            .addComponent(jLabel7)
                                                                            .addComponent(jLabel6)
                                                                            .addComponent(jLabel8)
                                                                            .addComponent(jLabel9)
                                                                            .addComponent(jLabel10)))
                                                            .addComponent(jLabel4))
                                                    .addGap(0, 112, Short.MAX_VALUE)))
                                    .addContainerGap())
            );
            jPanel3Layout.setVerticalGroup(
                    jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(videoName, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(videoLength)
                                                    .addComponent(jLabel2)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel7)
                                    .addGap(6, 6, 6)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel11))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel12))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29))
            );
            // add to map
            labelToPanel.put(menuLabel, jPanel3);
        }
        public JProgressBar getInformationPanelProgressBar() {
            return jProgressBar2;
        }
        public JLabel getCurentTimeLabel() {
            return jLabel12;
        }
    }
}
